##Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
##1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def build_fib_array(max_value)
  fib_array = [1,1]
  while fib_array[-1] <= max_value
    new_fib = fib_array[-1] + fib_array[-2]
    fib_array << new_fib
  end
  return fib_array
end

def sum_even_fibs(array)
  sum = 0
  array.each { |i| sum += i if i%2 == 0 }
  puts sum
end

sum_even_fibs(build_fib_array(4000000))
